### ISSUE TITLE
[ERROR] Dos tokens en el mismo párrafo

### ISSUE THREAD

**Issue by kchacon** [yosietserga/Autoplaceholder-CKEditor-Plugin#1]
Si uso dos tokens en el mismo párrafo, dejan de funcionar los tokens de ese párrafo.

**Comment by yosietserga** [comment]
Es necesario detalles de como replicar el error, cuales son los mensajes de error que indica la consola

**Comment by kchacon** [comment]
No muestra errores en la consola, pero no se puede asignar valores por defecto a los tokens que están dentro de un mismo párrafo (&lt;p&gt; ... &lt;/p&gt;)

**Comment by yosietserga** [comment]
repositorio actualizado con el fix

**Comment by kchacon** [comment]
El problema persiste cuando se carga data previamente almacenada
